### ISSUE TITLE
Collections for portfolio

### ISSUE THREAD

**Issue by neutraltone** [neutraltone/tonyphipps.co.uk#2]
Try using collections for portfolio

```
collections:
  projects:
    output: true
    permalink: /projects/:path/
```
